name: BuildTest-Cedar-Linux-x86_64-GCC-OpenMPI
run-name: ${{ github.actor }} is running BuildTest-Cedar-Linux-x86_64-GCC-OpenMPI 🚀

on:
  push:
    branches:
      - xxx
  pull_request:
    branches:
      - xxx

env:
  CMAKE_VERSION: 3.21.1
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build-and-test:
    runs-on: self-hosted
    strategy:
      matrix:
        build_type: [Debug, Release]
        gcc_version: [9.3.0, 10.3.0, 11.3.0]

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      GCC_VERSION: ${{ matrix.gcc_version }}

    steps:
      - name: Print GitHub context
        run: |
          echo "GitHub Event: ${{ github.event_name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Repository: ${{ github.repository }}"
          echo "Workspace: ${{ github.workspace }}"

      - name: Set up runner environment
        run: | 
          module --force purge
          module load StdEnv/2020
          module load cmake/3.21.4
          module load gcc/${{ env.GCC_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DENABLE_TESTING=ON -B ${{ env.BUILD_DIR }} -S .

      - name: Build with CMake
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Run unit tests
        run: ctest --test-dir ${{ env.BUILD_DIR }} --output-on-failure
