name: Build-Release
run-name: ${{ github.actor }} is running Build-Release 🚀

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CMAKE_VERSION: 3.21.1
  BUILD_TYPE: Release
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event_name ${{ github.event_name }}"
      - run: echo "runner.os  ${{ runner.os }} "
      - run: echo "github.ref ${{ github.ref }}"
      - run: echo "github.repository ${{ github.repository }}"

      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "github.workspace ${{ github.workspace }}"

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmake-version: ${{ env.CMAKE_VERSION }}

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: CMake configure step
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DENABLE_TESTING=ON -B ${{ env.BUILD_DIR }} -S .

      - name: CMake build step
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_DIR }}
          path: ${{ env.BUILD_DIR }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.BUILD_DIR }}

      - name: Run unit tests
        run: ctest --test-dir ${{ env.BUILD_DIR }}
