name: Build and Test
run-name: ${{ github.actor }} is running Build and Test 🚀

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - xxx

env:
  CMAKE_VERSION: 3.21.1
  BUILD_DIR: ${{ github.workspace }}/build

jobs:
  build-and-test:
    runs-on: self-hosted
    strategy:
      matrix:
        build_type: [Debug, Release]

    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
      - run: echo "github.event_name ${{ github.event_name }}"
      - run: echo "runner.os  ${{ runner.os }} "
      - run: echo "github.ref ${{ github.ref }}"
      - run: echo "github.repository ${{ github.repository }}"

      - name: Set up runner environment
        run: | 
          module --force purge
          module load StdEnv/2020
          module load cmake/3.21.4
          module load gcc/9.3.0

      - name: Checkout code
        uses: actions/checkout@v3

      - run: echo "github.workspace ${{ github.workspace }}"

      - name: CMake configure step
        run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DENABLE_TESTING=ON -B ${{ env.BUILD_DIR }} -S .

      - name: CMake build step
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Run unit tests
        run: ctest --test-dir ${{ env.BUILD_DIR }} --output-on-failure
