name: test-coverage
run-name: ${{ github.actor }} is running ${{ github.workflow }} 🚀

on:
  pull_request:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  pull-requests: write

jobs:
  build-coverage-main:
    uses: ./.github/workflows/build_coverage.yml
    with:
      branch: main
  
  build-coverage-current:
    uses: ./.github/workflows/build_coverage.yml
    with:
      branch: ${{ github.refname }}
  
  report-coverage:
    runs-on: ubuntu-latest
    needs: 
      - build-coverage-main
      - build-coverage-current

    steps:
      - name: Report coverage summary
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage
          message: |
            "Current branch coverage report"
            ```
            ${{ needs.build-coverage-current.outputs.coverage_summary }}
            ```
            "Main branch coverage report"
            ```
            ${{ needs.build-coverage-main.outputs.coverage_summary }}
            ```

      - name: Line coverage comparison
        run: |
          echo "Line coverage comparison"
          echo "Main branch: ${{ needs.build-coverage-main.outputs.lines_coverage }}"
          echo "Current branch: ${{ needs.build-coverage-current.outputs.lines_coverage }}"
      
      - name: Function coverage comparison
        run: |
          echo "Function coverage comparison"
          echo "Main branch: ${{ needs.build-coverage-main.outputs.functions_coverage }}"
          echo "Current branch: ${{ needs.build-coverage-current.outputs.functions_coverage }}"
      
      - name: Summary comparison
        run: |
          echo "Summary comparison"
          echo "Main branch: ${{ needs.build-coverage-main.outputs.coverage_summary }}"
          echo "Current branch: ${{ needs.build-coverage-current.outputs.coverage_summary }}"

      - name: List comparison
        run: |
          echo "List comparison"
          echo "Main branch: ${{ needs.build-coverage-main.outputs.coverage_list }}"
          echo "Current branch: ${{ needs.build-coverage-current.outputs.coverage_list }}"
    


